"""
model.py — Multiple Instance Learning (MIL) Model for VI-LUAD Binary Classification
=====================================================================================
This file defines a MIL model for slide-level classification. Read this
docstring to understand the model design. If you plan to use the baseline
as-is, that's all you need. If you plan to modify or replace it, dive into
the relevant code sections — a better model is the most direct path to a
higher score.

The core challenge: aggregating patches into a slide-level prediction
----------------------------------------------------------------------
A WSI is tiled into many patches by preprocess.py. Each patch yields a feature
vector, and each slide ends up as a variable-length set of those vectors (a small
biopsy might have 200 patches; a large resection might have 5,000). The model must
read this entire set and output ONE slide-level prediction.

This is an open-ended design problem — you are free to explore any architecture.
The baseline here uses Multiple Instance Learning (MIL), but other approaches are
perfectly valid and even encouraged.

The baseline MIL approach has two steps:
  1. Aggregation: pool the N variable-length patch features into one fixed-size
     slide embedding. We use mean pooling — the arithmetic mean of all patch
     feature vectors — so every patch contributes equally.
  2. Classification: pass the slide embedding through an MLP to get binary logits.

Two output classes (binary VI classification):
  0 — NONVITUMOR : tumor tissue from a patient WITHOUT vascular invasion
  1 — VITUMOR    : tumor tissue from a patient WITH vascular invasion

Key classes and functions in this file:
  - SlideDataset      : PyTorch Dataset that loads .pt feature files and labels
  - mil_collate_fn    : custom DataLoader collator for variable-length bags
  - get_dataloader    : convenience wrapper to build a DataLoader in one call
  - MILClassifier     : full model (mean pool + MLP head)
  - build_model       : factory function — call this from train_eval.py

Usage:
  from model import build_model, get_dataloader, LABEL_MAP, IDX_TO_LABEL

  model = build_model()
  train_loader = get_dataloader(train_records, features_dir="./features", shuffle=True)

Sanity check (no real data needed):
  python model.py
"""

import os
import json
from pathlib import Path
from typing import List, Dict, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader


# =============================================================================
# SECTION 0: CONSTANTS
# =============================================================================

# Map label strings (as they appear in the JSON splits) to integer class indices.
# We use this everywhere: in SlideDataset to convert labels, and in train_eval.py to
# interpret model predictions.
LABEL_MAP: Dict[str, int] = {
    "NONVITUMOR": 0,  # VI-negative: tumor slide from a patient WITHOUT vascular invasion
    "VITUMOR":    1,  # VI-positive: tumor slide from a patient WITH vascular invasion
}

# Reverse lookup: integer index → label string (useful when printing predictions)
IDX_TO_LABEL: Dict[int, str] = {v: k for k, v in LABEL_MAP.items()}

# Number of output classes: 2 for binary VITUMOR vs NONVITUMOR classification.
NUM_CLASSES: int = 2

# Patch feature dimension: default to 768 for cTransPath encoder.
# Must match preprocess.py output. If you use another encoder with a different
# output feature dimension, make sure to update here.
FEATURE_DIM: int = 768


# =============================================================================
# SECTION 1: DATASET AND DATA LOADING
# =============================================================================

class SlideDataset(Dataset):
    """
    PyTorch Dataset that loads patch features and slide-level labels.

    Each slide's features are stored as a .pt file (generated by preprocess.py)
    of shape (N_patches, feature_dim). This Dataset loads them on the fly in
    __getitem__, so only one slide's features are in memory at a time.

    Parameters
    ----------
    slide_records : list of dicts with keys: pid, filename, vi_label
                    (comes directly from the JSON split files in splits/)
    features_dir  : path to the directory where <slide_name>.pt files live
    label_map     : dict mapping label string to integer class index.
                    Defaults to LABEL_MAP defined at the top of this file.

    Example
    -------
    >>> import json
    >>> fold = json.load(open("splits/fold_0.json"))
    >>> train_set = SlideDataset(fold["train"], features_dir="./features")
    >>> features, label = train_set[0]
    >>> print(features.shape)   # e.g. torch.Size([1847, 768])
    >>> print(label)            # e.g. 0  (VITUMOR)
    """

    def __init__(self, slide_records: List[Dict], features_dir: str,
                 label_map: Dict[str, int] = LABEL_MAP):
        self.features_dir = Path(features_dir)
        self.label_map = label_map

        # Walk through the provided records and keep only slides whose .pt
        # feature file is already on disk.  Slides may be missing if preprocess.py
        # hasn't finished yet, or if they were skipped due to no tissue found.
        self.samples = []
        skipped = 0
        for record in slide_records:
            # Derive the feature file name from the slide filename:
            #   "10499.svs"  →  "10499.pt"
            stem = Path(record["filename"]).stem
            feat_path = self.features_dir / f"{stem}.pt"
            if feat_path.exists():
                self.samples.append({
                    "feat_path": feat_path,
                    "label":     label_map[record["vi_label"]],
                    "vi_label":  record["vi_label"],
                    "pid":       record["pid"],
                    "filename":  record["filename"],
                })
            else:
                skipped += 1

        if skipped > 0:
            print(f"  [SlideDataset] WARNING: {skipped} slides are missing feature "
                  f"files — did preprocess.py finish? They will be skipped.")
        print(f"  [SlideDataset] Ready: {len(self.samples)} slides "
              f"from '{features_dir}'.")

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, int]:
        """
        Load and return one slide's features and its class label.

        Returns
        -------
        features : torch.Tensor of shape (N_patches, feature_dim)
                   All patch feature vectors for this slide.
                   N_patches varies per slide — see mil_collate_fn below.
        label    : int — class index (0=VITUMOR, 1=NONVITUMOR, 2=NONTUMOR)
        """
        sample = self.samples[idx]
        # Load the pre-extracted feature tensor from disk.
        # weights_only=True is a security flag that prevents loading arbitrary
        # Python objects — safe here since the file contains only tensors.
        try:
            features = torch.load(sample["feat_path"], weights_only=True)
        except TypeError:
            # Older PyTorch versions don't support weights_only — fall back
            features = torch.load(sample["feat_path"])
        return features, sample["label"]


def mil_collate_fn(batch: List[Tuple[torch.Tensor, int]]):
    """
    Custom collate function for variable-length MIL bags.

    Why do we need a custom collate function?
    -----------------------------------------
    PyTorch's default collate tries to stack tensors from a batch into a single
    tensor, which requires all tensors to have the same shape. But different
    slides have different numbers of patches (variable N). Stacking would fail.

    Solution: return a Python list of feature tensors (one per slide in the
    batch) rather than a stacked tensor. The training loop in train_eval.py
    iterates over this list and processes each slide individually.

    Parameters
    ----------
    batch : list of (features, label) tuples from SlideDataset.__getitem__

    Returns
    -------
    features_list : list of torch.Tensor, each of shape (N_i, feature_dim)
                    where N_i is the (different) patch count for slide i
    labels        : torch.LongTensor of shape (batch_size,)
    """
    features_list = [item[0] for item in batch]
    labels = torch.tensor([item[1] for item in batch], dtype=torch.long)
    return features_list, labels


def get_dataloader(slide_records: List[Dict],
                   features_dir: str,
                   batch_size: int = 1,
                   shuffle: bool = True,
                   num_workers: int = 0) -> DataLoader:
    """
    Build a DataLoader for MIL training or evaluation.

    We recommend batch_size=1: each gradient step uses one slide.  This is
    the most common setting in digital pathology MIL because slides have very
    different patch counts and a batch of one already contains hundreds of
    patches driving the gradient.

    Parameters
    ----------
    slide_records : list of slide dicts (from the split JSON)
    features_dir  : directory containing <slide>.pt feature files
    batch_size    : slides per batch (1 is recommended)
    shuffle       : True for training, False for evaluation
    num_workers   : parallel data loading workers (0 = load in main process)

    Returns
    -------
    DataLoader configured with mil_collate_fn for variable-length bags
    """
    dataset = SlideDataset(slide_records, features_dir)
    loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        collate_fn=mil_collate_fn,
        num_workers=num_workers,
        pin_memory=torch.cuda.is_available(),
    )
    return loader


# =============================================================================
# SECTION 2: MIL MODEL — MEAN POOLING + MLP HEAD
# =============================================================================

class MILClassifier(nn.Module):
    """
    Full slide-level MIL classifier for binary VI-LUAD prediction
    (VITUMOR vs NONVITUMOR).

    Architecture summary
    --------------------
      Input  : H — bag of patch features, shape (N, feature_dim), N varies per slide
      Step 1 : Mean pooling — H.mean(dim=0) → (1, feature_dim) slide embedding.
               All patches contribute equally; no extra parameters needed.
      Step 2 : MLP classification head:
                  Linear(feature_dim → hidden_dim) + ReLU + Dropout
                  Linear(hidden_dim → 2)
      Output : logits of shape (1, 2)  [NONVITUMOR, VITUMOR]

    The model is trained with cross-entropy loss. During inference, apply
    softmax to logits to get class probabilities, or argmax for the predicted
    class.

    Parameters
    ----------
    feature_dim : patch feature dimension (default 768 — matches cTransPath encoder
                  but subject to change)
    hidden_dim  : size of the hidden layer in the MLP head. Try 128, 256, or 512.
    num_classes : number of output classes (3 — don't change)
    dropout     : dropout probability after the ReLU in the MLP head.
                  Dropout randomly zeros hidden units during training to
                  regularize against overfitting. Set to 0.0 to disable.
    """

    def __init__(self, feature_dim: int = FEATURE_DIM,
                 hidden_dim: int = 256,
                 num_classes: int = NUM_CLASSES,
                 dropout: float = 0.25):
        super().__init__()

        # MLP classification head — maps slide embedding to logits.
        # A single hidden layer keeps the model lightweight.
        # Output size = num_classes = 2 (NONVITUMOR, VITUMOR).
        self.classifier = nn.Sequential(
            nn.Linear(feature_dim, hidden_dim),
            nn.ReLU(inplace=True),
            nn.Dropout(p=dropout),
            nn.Linear(hidden_dim, num_classes),
        )

    def forward(self, H: torch.Tensor) -> Tuple[torch.Tensor, None]:
        """
        Forward pass for a single slide's bag of features.

        Parameters
        ----------
        H : torch.Tensor of shape (N, D)
            All patch feature vectors for one slide.

        Returns
        -------
        logits : torch.Tensor of shape (1, 2)  [NONVITUMOR score, VITUMOR score]
                 Raw class scores (pass through softmax for probabilities).
        None   : placeholder — train_eval.py uses  logits, _ = model(features),
                 so we return a two-element tuple to keep the interface consistent.
        """
        # Aggregate the bag: (N, D) → (1, D) by averaging across all patches
        z = H.mean(dim=0, keepdim=True)  # (1, D)

        # Classify the slide embedding: (1, D) → (1, num_classes)
        logits = self.classifier(z)

        return logits, None

    def predict_proba(self, H: torch.Tensor) -> Tuple[torch.Tensor, None]:
        """
        Convenience method: run inference and return class probabilities.

        Wraps forward() in torch.no_grad() and applies softmax so you get
        probabilities instead of raw logits.

        Parameters
        ----------
        H : torch.Tensor of shape (N, D)

        Returns
        -------
        probs : torch.Tensor of shape (1, num_classes) — probabilities sum to 1
        None  : placeholder (no per-patch weights in mean-pooling model)
        """
        self.eval()
        with torch.no_grad():
            logits, _ = self.forward(H)
            probs = torch.softmax(logits, dim=-1)
        return probs, None


# =============================================================================
# SECTION 3: FACTORY FUNCTION
# =============================================================================

def build_model(feature_dim: int = FEATURE_DIM,
                hidden_dim: int = 256,
                num_classes: int = NUM_CLASSES,
                dropout: float = 0.25) -> MILClassifier:
    """
    Instantiate and return a new MILClassifier with random weights.

    This is the function you should import in train_eval.py:

        from model import build_model
        model = build_model().to(device)

    Hyperparameters to experiment with
    ------------------------------------
    hidden_dim : controls model capacity.
        128  → fewer parameters, less risk of overfitting (good for small datasets)
        256  → balanced (default)
        512  → more capacity, may need stronger regularization

    dropout : regularization strength.
        0.0  → no dropout (try if training loss is high / underfitting)
        0.25 → light regularization (default)
        0.5  → stronger regularization (try if validation accuracy is lower
               than training accuracy by a large margin)

    Parameters
    ----------
    feature_dim : patch feature dimension (default 768; subject to change)
    hidden_dim  : hidden size for the MLP head
    num_classes : number of output classes (3 — do not change)
    dropout     : dropout probability in the MLP head

    Returns
    -------
    MILClassifier with randomly initialized weights, ready for training.
    """
    model = MILClassifier(
        feature_dim=feature_dim,
        hidden_dim=hidden_dim,
        num_classes=num_classes,
        dropout=dropout,
    )

    # Count and display the total number of learnable parameters.
    n_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(f"MILClassifier (mean pooling) built: {n_params:,} trainable parameters")
    print(f"  feature_dim={feature_dim}  hidden_dim={hidden_dim}  "
          f"num_classes={num_classes}  dropout={dropout}")

    return model


# =============================================================================
# SECTION 4: QUICK SANITY CHECK  (python model.py)
# =============================================================================

if __name__ == "__main__":
    """
    Run a quick forward-pass test to verify the model and dataset code work.
    This uses randomly generated features — no real WSI data needed.

        python model.py
    """
    print("=" * 60)
    print("model.py — Quick Sanity Check")
    print("=" * 60)

    # --- Build the model ---
    model = build_model()
    model.eval()

    # --- Simulate a bag (one slide with 1,000 random patch features) ---
    N_patches = 1000
    fake_features = torch.randn(N_patches, FEATURE_DIM)
    print(f"\nSimulated slide bag: {N_patches} patches × {FEATURE_DIM} features")

    # --- Forward pass ---
    with torch.no_grad():
        logits, attn_weights = model(fake_features)

    probs = torch.softmax(logits, dim=-1)
    predicted_idx = logits.argmax(dim=-1).item()

    # --- Print results ---
    print(f"\nForward pass output shapes:")
    print(f"  logits      : {tuple(logits.shape)}")
    print(f"  probs       : {tuple(probs.shape)}")
    print(f"  attn_weights: {attn_weights}  (None — no per-patch weights in mean pooling)")

    print(f"\nClass probabilities:")
    for idx, prob in enumerate(probs[0].tolist()):
        marker = " ← predicted" if idx == predicted_idx else ""
        print(f"  {IDX_TO_LABEL[idx]:>12s} (class {idx}): {prob:.4f}{marker}")

    # --- Simulate the collate function with two slides of different sizes ---
    print("\nTesting mil_collate_fn with two slides of different sizes...")
    fake_batch = [
        (torch.randn(800, FEATURE_DIM),  1),  # slide 1: 800 patches, label=VITUMOR
        (torch.randn(1500, FEATURE_DIM), 0),  # slide 2: 1500 patches, label=NONVITUMOR
    ]
    features_list, labels = mil_collate_fn(fake_batch)
    print(f"  features_list: {len(features_list)} slides, "
          f"shapes={[tuple(f.shape) for f in features_list]}")
    print(f"  labels: {labels.tolist()}  "
          f"({[IDX_TO_LABEL[l.item()] for l in labels]})")

    print("\nAll checks passed! model.py is working correctly.")